node_revision_delete.settings:
  type: mapping
  mapping:
    langcode:
      type: string
      label: 'Language code'
    _core:
      type: _core_config_info
    node_types:
      type: sequence
      label: 'Node types'
      sequence:
        - type: node_revision_delete.node_type

node_revision_delete.node_type:
  type: mapping
  mapping:
    method:
      type: string
      label: Delete method
    keep:
      type: integer
      label: Number to keep
    age:
      type: string
      label: Age of revision to delete
